// Generated by nuxt-seo-utils.assets

declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/schema'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/ads.txt' | '/ecosystem.config.js' | '/favicon.ico' | '/_robots.txt' | '/img/articles/catnip-planting-diary/Day1.gif' | '/img/articles/catnip-planting-diary/Day2中午.webp' | '/img/articles/catnip-planting-diary/Day3上午懶得發芽組.webp' | '/img/articles/catnip-planting-diary/Day3上午頭好壯壯組.webp' | '/img/articles/catnip-planting-diary/Day3下午.webp' | '/img/articles/catnip-planting-diary/Day4下午.webp' | '/img/articles/catnip-planting-diary/Day5上午.webp' | '/img/articles/catnip-planting-diary/Day5下午.webp' | '/img/articles/catnip-planting-diary/Day6下午.webp' | '/img/articles/catnip-planting-diary/Day7.webp' | '/img/articles/catnip-planting-diary/Day8.webp' | '/img/articles/catnip-planting-diary/小麥種子及水培盒.webp' | '/img/articles/catnip-planting-diary/小麥種子近照.webp' | '/img/articles/catnip-planting-diary/成果.mp4' | '/img/articles/catnip-planting-diary/斯帕全身照.webp' | '/img/articles/catnip-planting-diary/斯帕試吃貓草.gif' | '/img/articles/two-level-hierarchica-checkbox-selector/成果展示.webp' | '/img/articles/two-level-hierarchica-checkbox-selector/步驟一.webp' | '/img/articles/two-level-hierarchica-checkbox-selector/步驟三.webp' | '/img/articles/two-level-hierarchica-checkbox-selector/步驟二.webp' | '/img/articles/catnip-planting-tutorial/斯帕.webp' | '/img/articles/catnip-planting-tutorial/貓草.webp' | (string & Record<never, never>)
  type JsFiles = '/ecosystem.config.js' | (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}
export {}
